### ISSUE TITLE
Adapter crashes when target not reachable (unhandled promise rejection)

### ISSUE THREAD

**Issue by kgerlich** [iobroker-community-adapters/ioBroker.yamaha#20]
yamaha.0 | 2020-05-14 10:04:52.925 | info | (16077) Terminated (NO_ERROR): Without reason
yamaha.0 | 2020-05-14 10:04:52.924 | info | (16077) terminating
yamaha.0 | 2020-05-14 10:04:52.913 | error | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
yamaha.0 | 2020-05-14 10:04:52.913 | error | (16077) Error: getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:80
yamaha.0 | 2020-05-14 10:04:52.913 | error | (16077) unhandled promise rejection: getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:80
Unhandled | 2020-05-14 10:04:52.912 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
yamaha.0 | 2020-05-14 10:04:52.904 | error | at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
yamaha.0 | 2020-05-14 10:04:52.904 | error | (16077) Error: getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:80
yamaha.0 | 2020-05-14 10:04:52.903 | error | (16077) unhandled promise rejection: getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:80
Unhandled | 2020-05-14 10:04:52.902 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**To Reproduce**  
1. turn Yamaha adapter off or disconnect from network

**Versions:**  
 - Adapter version: 0.3.21
 - JS-Controller version:  3.1.4
 - Node version: 10.20.1
 - Operating system: Linux iobroker 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:12:47 UTC 2020 i686 i686 i686 GNU/Linux

**Additional context**  
32bit system

**Comment by Apollon77** [comment]
getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:

means that the DNS lookup for that name was not possinle.... right, adapter should not crash but maybe that helps for you

**Comment by kgerlich** [comment]
> getaddrinfo ENOTFOUND yamaha.fritz.box yamaha.fritz.box:
> 
> means that the DNS lookup for that name was not possinle.... right, adapter should not crash but maybe that helps for you

Hi thanks for the reply.

Obviously my Yamaha receiver is not reachable since it's sometimes completely turned off. Not sure what changed in the Yamaha adapter (regular and community) that it suddenly exhibits this error. I'll debug if I find the time.

**Comment by Apollon77** [comment]
Please recheck with 0.4.0 and provide log again
