### ISSUE TITLE
Einige Infos werden nach einiger Zeit mehr aktualisiert

### ISSUE THREAD

**Issue by Moko0815** [iobroker-community-adapters/ioBroker.yamaha#223]
**Describe the bug**  
Nach einiger Zeit (ca 1-2 Tagen) werden die DAB Informationen nicht mehr aktualisiert. Es steht heute z.B. bei yamaha.0.Realtime.DAB.DABDATETIME drin: 14NOV'21 13:03.
Ebenso die Objekte unter MAIN (z.B. Mute, Pwr, Straight) werden nicht aktualisiert bei einer Änderung am Receiver.
Der Receiver läuft bei mir fast den ganzen Tag. 
Spiele ich ein Backup vom ioBroker ein, läuft es wieder 1-2 Tage.
Löschen des Adapters + Neuinstallation geht überhaupt nicht, weil dann bei den Objekten der ganze yamaha.0.Realtime.DAB Schlüssel fehlt (ebenso z.B. auch Netradio und Server). Seltsamerweise ging es einmal, sonst würde mir das Backup einspielen nicht helfen.
Andere Infos, z.B. Lautstärke wird aktualisiert, nur eben die Objekte im DAB-Zweig nicht :(

 - Adapter version: 0.4.0
 - JS-Controller version: 3.3.18
 - Node version:  v14.18.1
 - Operating system: Linux raspberrypi 5.10.63-v7l+
- Receiver: Yamaha RX-S602

Einstellungen im Adapter: Abfrageintervall 10
Alle 3 Punkte sind aktiviert:
"Echtzeitmodus verwenden"
"Aktualisieren Sie alle Datenpunkte bei einem Echtzeitereignis"
"Intervall zum Pingen der Echtzeitverbindung in Sekunden (0 = keine)"

**Comment by Apollon77** [comment]
Bitte Debug Log aktivieren und am besten da reinschauen ... ggf hier posten oder hochladen ...vllt ist ja was zu sehen

**Comment by Moko0815** [comment]
Ich hoffe das ist das, was Du meinst: Kenne mich leider mit den Logfiles noch nicht so gut aus.
Adapter ist grün, Verbindung steht.
> yamaha.0
> 	2021-11-17 11:49:41.326	debug	Y5: @MAIN:PWR=? written
> yamaha.0
> 	2021-11-17 11:49:41.324	debug	send called with writable=false
> yamaha.0
> 	2021-11-17 11:49:40.344	debug	Y5: setReconnectTimer (2000)
> yamaha.0
> 	2021-11-17 11:49:40.343	debug	Y5: Connection closed, hadError=true
> yamaha.0
> 	2021-11-17 11:49:40.341	debug	Y5: error: -104 read ECONNRESET
> yamaha.0
> 	2021-11-17 11:49:40.325	debug	Y5: @ZONE2:PWR=? written
> yamaha.0
> 	2021-11-17 11:49:40.324	debug	Y5: @MAIN:PWR=? written
> yamaha.0
> 	2021-11-17 11:49:40.322	debug	Y5: connected!
> yamaha.0
> 	2021-11-17 11:49:40.320	debug	Y5: on connect
> yamaha.0
> 	2021-11-17 11:49:40.317	debug	Y5: trying to connect...
> yamaha.0
> 	2021-11-17 11:49:40.315	debug	Y5: reconnecting...
> yamaha.0
> 	2021-11-17 11:49:40.298	debug	Y5: @MAIN:PWR=? written
> yamaha.0
> 	2021-11-17 11:49:40.295	debug	send called with writable=false
> yamaha.0
> 	2021-11-17 11:49:39.297	debug	Y5: @MAIN:PWR=? written
> yamaha.0
> 	2021-11-17 11:49:39.295	debug	send called with writable=false
> yamaha.0
> 	2021-11-17 11:49:38.314	debug	Y5: setReconnectTimer (2000)
> yamaha.0
> 	2021-11-17 11:49:38.313	debug	Y5: Connection closed, hadError=true
> yamaha.0
> 	2021-11-17 11:49:38.311	debug	Y5: error: -104 read ECONNRESET
> yamaha.0

**Comment by Apollon77** [comment]
ECONNRESET bedeutet das das Gerät die Verbindung ablehnt ... da kann der Adapter nix für. Starte das vllt mal komplett neu (Strom weg und so)

**Comment by Moko0815** [comment]
Stecker raus hat geholfen. Krass.... Danke, da wäre ich nie drauf gekommen.
Übrigens bleibt der Adapter grün (auch nach Neustart), wenn der Receiver komplett stromlos ist, und er (der Adapter) ist der Meinung er sei verbunden und empfängt Lebenszeichen ;)

**Comment by Apollon77** [comment]
Ja das geht aber nur eine Zeit lang. Wie lange steht in den Settings vom Adapter ... Die verbidnung wird erst nach einer gewissen zeit für "tod" erklärt" weil das Gerät im standby auch teilweise nicht antwortet
