### ISSUE TITLE
Scenes, Power und weitere Funktionen reagieren nicht mehr

### ISSUE THREAD

**Issue by eljarno** [iobroker-community-adapters/ioBroker.yamaha#381]
Seit einiger Zeit funktioniert bei mir Power und die Scenenen nicht mehr. Auch mute reagiert unter anderem nicht mehr.

**Comment by mcm1957** [comment]
Please add the minimum revision information:

Adapter version:
js-controller version:
admin version:
node version.
npm version:
OS type / Version

**Comment by Garfonso** [comment]
siehst du irgendwas dazu im log?

**Comment by mcm1957** [comment]
Since August...

no log
no version info

Lets close for now.
Please open a new issue if problem still exists and add all version informations and a debug log.

**Comment by eljarno** [comment]
Sorry forgot to get back to it. Es hing mit Fehlern im iobroker selbst zusammen. Konnte es also selbst fixen. Danke trotzdem
