### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [iobroker-community-adapters/ioBroker.yamaha#4]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/iobroker-community-adapters/ioBroker.yamaha-community

- [x] [E020] Name of adapter in package.json must be lowercase and be equal to "iobroker.yamaha-community". Now is "undefined"
- [x] [E019] Invalid repository URL: https://github.com/iobroker-community-adapters/ioBroker.yamaha. Expected: git+https://github.com/iobroker-community-adapters/ioBroker.yamaha-community.git
- [x] [E103] common.name in io-package.json must be equal to "yamaha-community". Now is yamaha
- [x] [E200] Not found on npm. Please publish
- [x] [E300] Not found on travis. Please setup travis
- [x] [E605] No actual year found in copyright. Please add "Copyright (c) 2015-2021 soef <soef@gmx.net>" at the end of README.md
- [x] [E701] No actual year found in LICENSE. Please add "Copyright (c) 2015-2021 soef <soef@gmx.net>" at the start of LICENSE

I have also found warnings that may be fixed if possible.

- [x] [W400] Cannot find "yamaha-community" in latest repository

Thanks,
your automatic adapter checker.

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?

**Comment by Apollon77** [comment]
should be fixed in 0.4.0

**Comment by Sneak-L8** [comment]
fixed in 0.4.1
