### ISSUE TITLE
Please report this to the developer. Objekt .... is invalid

### ISSUE THREAD

**Issue by metaxa1** [iobroker-community-adapters/ioBroker.yamaha#412]
Ich hoffe ich bin hier richtig, dass hier dem deloper zu reporten?

Ich habe bei einem Restart meines aktuellen System

- OS Debian bookworm 12
- js-Controller 5.0.12
- Admin 6.12.0
- ioBroker.yamaha 0.3.19
- Node.js v18.18.2
- NPM 9.8.1

folgende Warnmeldungen im Log

`
yamaha-community.0 | 2023-11-10 23:11:52.040 | info | starting. Version 0.3.19 (non-npm: iobroker-community-adapters/ioBroker.yamaha-community#5020b47aad87b079fd1d611f4eb4ffff66e4e3d3) in /opt/iobroker/node_modules/iobroker.yamaha-community, node: v18.18.2, js-controller: 5.0.12
-- | -- | -- | --
yamaha-community.0 | 2023-11-10 23:11:51.993 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.992 | warn | Object yamaha-community.0.powerAllZones is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.949 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.948 | warn | Object yamaha-community.0.zone4 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.901 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.900 | warn | Object yamaha-community.0.zone3 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.857 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.857 | warn | Object yamaha-community.0.zone2 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.814 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.813 | warn | Object yamaha-community.0.zone1 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.753 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.752 | warn | Object yamaha-community.0.pureDirect is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.705 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.704 | warn | Object yamaha-community.0.hdmiOut2 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.661 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.660 | warn | Object yamaha-community.0.hdmiOut1 is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.613 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.613 | warn | Object yamaha-community.0.Commands.partyModeVolumeDown is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.569 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.568 | warn | Object yamaha-community.0.Commands.partyModeVolumeUp is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.525 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.525 | warn | Object yamaha-community.0.partyMode is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.481 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.481 | warn | Object yamaha-community.0.adaptiveDRC is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.437 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.436 | warn | Object yamaha-community.0.extraBass is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.393 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.392 | warn | Object yamaha-community.0.YPAOVolume is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.349 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.348 | warn | Object yamaha-community.0.Commands.skip is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.305 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.304 | warn | Object yamaha-community.0.Commands.rewind is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.261 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.260 | warn | Object yamaha-community.0.Commands.skip is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.213 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.212 | warn | Object yamaha-community.0.Commands.pause is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.165 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.164 | warn | Object yamaha-community.0.Commands.stop is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.121 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.121 | warn | Object yamaha-community.0.refresh is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.073 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.073 | warn | Object yamaha-community.0.power is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:51.024 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:51.023 | warn | Object yamaha-community.0.mute is invalid: obj.common.min has an invalid type! Expected "number", received "boolean"
yamaha-community.0 | 2023-11-10 23:11:50.972 | warn | This object will not be created in future versions. Please report this to the developer.
yamaha-community.0 | 2023-11-10 23:11:50.972 | warn | Object yamaha-community.0.Commands.toggleMute is invalid: Default value has to be type "boolean" but received type "number"
`

**Comment by mcm1957** [comment]
An sich bist du hier richtigr

ABER der Adapter wurde bereits 2020 von yahama-community auf yahama (zurück) umbenannt. Er steht mittlerweile in Version 0.5.3 zur Verfügung.

Bitte aktualisiere und teste den Adapter in der aktuellen Version. Sollten dann noch Probleme auftreten, öffne bitte ein neues Issue.

**ACHTUNG: Es ist mir nicht bekannt, ob die aktuelle Version des Adapters mit deiner alten Version kompatibel ist.**

**Comment by metaxa1** [comment]
Danke für deine Aufklärung, diese Entwicklung ging gänzlich an mir vorüber. Die von dir empfohlene Version arbeitet scheinbar ohne Probleme bei mir. Aktualisieren ist schon auf Grund des anderen Namens bei mir nicht möglich. Lieben Dank für deinen Hinweis!

**Comment by mcm1957** [comment]
Ja ist mir schon klar, dass da Aktualisiserung nicht ging.
Umbenungsaktionen waren auch - sagen wir mal - unglücklich. 

Hauptsache es funktioniert im Moment alles bei dir.
