### ISSUE TITLE
Changelog ?

### ISSUE THREAD

**Issue by wendy2702** [iobroker-community-adapters/ioBroker.yamaha#68]
Hi,

at iobroker Admin i can see that the latest Version is 0.4.0 but the changelog did not provide any information about what and who has done the latest changes.

Can you please update the changelog!

And can the changelog at Admin, NPM and Git be alligned:

Admin

![grafik](https://user-images.githubusercontent.com/33424168/100202613-d631e900-2f01-11eb-8c81-9931930757b5.png)

NPM & GIT:

![grafik](https://user-images.githubusercontent.com/33424168/100202685-efd33080-2f01-11eb-911a-e28be4c84ddf.png)

Kind regards

**Comment by Apollon77** [comment]
thank you for the report. Was just a missing adjustment. 0.3.21 was only existing on github shortly
